locale: {english: en, vietnamese: vi}
validates:
  {maximum_email: 255,
  maximum_name: 50,
  minimum_password: 6}
image:
  {gravatar_user_size: 50,
  gravatar_user_default_size: 80,
  show_follow_size: 30,
  maximum_size: 5,
  file_type: "image/jpeg, image/gif, image/png"}
session: {remember_true: 1}
paginate: {per_page: 10}
expired: {reset_pass: 2}
micropost: {maximum_content: 140}
